{
 "title": "solar-power-history",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "History",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sonoff",
     "query": "SELECT mean(\"Voltage\") AS \"Voltage\", mean(\"Current\") AS \"Current\", mean(\"ApparentPower\") AS \"ApparentPower\", mean(\"ApparentPower\") AS \"ApparentPower\" FROM \"sonoff\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current" ], "type": "alias" }
      ],
      [
       { "params": [ "ApparentPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ApparentPower" ], "type": "alias" }
      ],
      [
       { "params": [ "Factor" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Factor" ], "type": "alias" }
      ],
      [
       { "params": [ "Period" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Period" ], "type": "alias" }
      ],
      [
       { "params": [ "Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power" ], "type": "alias" }
      ],
      [
       { "params": [ "ReactivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ReactivePower" ], "type": "alias" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Produced energy (Tasmota)",
   "type": "singlestat",
   "description": "Most accurate because accumulated by the measuring device itself",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "kwatth",
   "valueName": "range",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sonoff",
     "query": "SELECT mean(\"Total\") FROM \"sonoff\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced energy / day (Tasmota Period)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sonoff",
     "select": [
      [
       { "params": [ "Period" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last received data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT time, Voltage FROM \"sonoff\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced energy (Tasmota Period)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "format": "watth",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sonoff",
     "query": "SELECT mean(\"Total\") FROM \"sonoff\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Period" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced energy (received via MQTT every ~5 mins)",
   "type": "singlestat",
   "description": "SELECT math() from https://community.openhab.org/t/sum-energy-values-stored-in-influxdb/33756/9",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "watth",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "sonoff",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "/60/60" ], "type": "math" },
       { "params": [ "Leistung" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced energy / day (MQTT)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sonoff",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/60/60" ], "type": "math" },
       { "params": [ "Leistung" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}